sh scripts/train_test_single_task.sh data align-rope
sh scripts/train_test_single_task.sh data assembling-kits-seq
sh scripts/train_test_single_task.sh data palletizing-boxes
sh scripts/train_test_single_task.sh data towers-of-hanoi
sh scripts/train_test_single_task.sh data assembling-kits
sh scripts/train_test_single_task.sh data align-box-corner
sh scripts/train_test_single_task.sh data manipulating-rope
sh scripts/train_test_single_task.sh data packing-boxes
sh scripts/train_test_single_task.sh data place-red-in-green
sh scripts/train_test_single_task.sh data put-block-in-bowl
sh scripts/train_test_single_task.sh data task
sh scripts/train_test_single_task.sh data packing-boxes-pairs
sh scripts/train_test_single_task.sh data sweeping-piles
sh scripts/train_test_single_task.sh data separating-piles
sh scripts/train_test_single_task.sh data stack-block-pyramid-seq
sh scripts/train_test_single_task.sh data towers-of-hanoi-seq
sh scripts/train_test_single_task.sh data packing-shapes
sh scripts/train_test_single_task.sh data stack-block-pyramid
sh scripts/train_test_single_task.sh data block-insertion
sh scripts/train_test_single_task.sh data packing-google-objects
sh scripts/train_test_single_task.sh data color-coordinated-ball-stacking
sh scripts/train_test_single_task.sh data cylinder-ring-stack
sh scripts/train_test_single_task.sh data color-ordered-blocks-on-pallet
sh scripts/train_test_single_task.sh data build-cylinder-structure
sh scripts/train_test_single_task.sh data build-bridge
sh scripts/train_test_single_task.sh data pyramid-blocks-assemble
sh scripts/train_test_single_task.sh data sort-and-assemble-block-castle
sh scripts/train_test_single_task.sh data stack-blocks-in-container
sh scripts/train_test_single_task.sh data corner-sort-cylinders
sh scripts/train_test_single_task.sh data align-pair-colored-blocks-along-line
sh scripts/train_test_single_task.sh data color-specific-container-fill
sh scripts/train_test_single_task.sh data colored-cylinder-in-square
sh scripts/train_test_single_task.sh data construct-colorful-arch
sh scripts/train_test_single_task.sh data color-coordinated-ball-insertion
sh scripts/train_test_single_task.sh data insert-sphere-into-container
sh scripts/train_test_single_task.sh data build-wheel
sh scripts/train_test_single_task.sh data color-coordinated-sphere-and-cylinder-assembly
sh scripts/train_test_single_task.sh data push-piles-into-letter
sh scripts/train_test_single_task.sh data color-coordinated-zone-stacking
sh scripts/train_test_single_task.sh data create-pyramid-with-color-coded-ells
sh scripts/train_test_single_task.sh data color-coordinated-arch-construction
sh scripts/train_test_single_task.sh data color-coordinated-sphere-insertion
sh scripts/train_test_single_task.sh data move-piles-along-line
sh scripts/train_test_single_task.sh data insert-ell-along-square-path
sh scripts/train_test_single_task.sh data multi-level-block-construction
sh scripts/train_test_single_task.sh data build-car
sh scripts/train_test_single_task.sh data color-coded-blocks-on-corner
sh scripts/train_test_single_task.sh data multi-level-insertion-and-zone-matching
sh scripts/train_test_single_task.sh data color-coordinated-insertion
sh scripts/train_test_single_task.sh data triangle-block-arrangement
sh scripts/train_test_single_task.sh data ball-in-bowl-obstacle-course-new
sh scripts/train_test_single_task.sh data colorful-block-tower-on-cylinder-base
sh scripts/train_test_single_task.sh data manipulating-two-ropes
sh scripts/train_test_single_task.sh data construct-corner-building
sh scripts/train_test_single_task.sh data color-coordinated-block-bridge
sh scripts/train_test_single_task.sh data color-sequenced-sphere-placement
sh scripts/train_test_single_task.sh data construct-corner-blocks
sh scripts/train_test_single_task.sh data sort-insert-color-coordinated-blocks
sh scripts/train_test_single_task.sh data color-ordered-container-arrangement
sh scripts/train_test_single_task.sh data symmetric-block-bridge-construction
sh scripts/train_test_single_task.sh data connect-boxes-with-rope
sh scripts/train_test_single_task.sh data vertical-insertion-blocks
sh scripts/train_test_single_task.sh data cylinder-stand-alignment
sh scripts/train_test_single_task.sh data color-coordinated-zone-arrangement
sh scripts/train_test_single_task.sh data insert-blocks-lineup
sh scripts/train_test_single_task.sh data create-pyramid-blocks-and-container
sh scripts/train_test_single_task.sh data mix-piles
sh scripts/train_test_single_task.sh data color-sequenced-pyramid-packing
sh scripts/train_test_single_task.sh data color-coordinated-cylinder-pyramid
sh scripts/train_test_single_task.sh data sweep-and-sort-blocks
sh scripts/train_test_single_task.sh data multi-level-pyramid-construction
sh scripts/train_test_single_task.sh data guided-block-path
sh scripts/train_test_single_task.sh data rainbow-stack
sh scripts/train_test_single_task.sh data color-ordered-insertion-new
sh scripts/train_test_single_task.sh data mixed-color-block-barrier-insertion
sh scripts/train_test_single_task.sh data color-coordinated-block-shifting
sh scripts/train_test_single_task.sh data align-balls-in-colored-zones
sh scripts/train_test_single_task.sh data multicolor-block-bridge
sh scripts/train_test_single_task.sh data sequential-insertion-and-stacking
sh scripts/train_test_single_task.sh data insertion-in-color-sequenced-zones
sh scripts/train_test_single_task.sh data align-spheres-in-colored-zones
sh scripts/train_test_single_task.sh data color-blocks-in-cylinder-maze
sh scripts/train_test_single_task.sh data color-coordinated-sphere-on-pallet-pyramid
sh scripts/train_test_single_task.sh data sort-and-stack-clr-blocks
sh scripts/train_test_single_task.sh data corner-block-challenge
sh scripts/train_test_single_task.sh data sequential-block-insertion
sh scripts/train_test_single_task.sh data sphere-container-color-match
sh scripts/train_test_single_task.sh data stack-color-coordinated-blocks
sh scripts/train_test_single_task.sh data assemble-single-car
sh scripts/train_test_single_task.sh data color-structured-block-tower
sh scripts/train_test_single_task.sh data color-sorted-block-race
sh scripts/train_test_single_task.sh data align-balls-in-colored-boxes
sh scripts/train_test_single_task.sh data color-coordinated-cylinder-ball-match
sh scripts/train_test_single_task.sh data build-house
sh scripts/train_test_single_task.sh data align-cylinders-in-zones
sh scripts/train_test_single_task.sh data sphere-align-stand
sh scripts/train_test_single_task.sh data ball-in-bowl-obstacle-course
sh scripts/train_test_single_task.sh data color-coordinated-block-tower
sh scripts/train_test_single_task.sh data color-sorted-container-stack
sh scripts/train_test_single_task.sh data color-coordinated-cylinder-stand-assembly
sh scripts/train_test_single_task.sh data color-ordered-insertion
sh scripts/train_test_single_task.sh data block-pyramid-with-limited-space
sh scripts/train_test_single_task.sh data color-cued-ball-corner-sorting
sh scripts/train_test_single_task.sh data sorting-blocks-into-pallets
sh scripts/train_test_single_task.sh data place-ball-in-elevated-bowl
sh scripts/train_test_single_task.sh data Four-corner-pyramid-challenge
sh scripts/train_test_single_task.sh data colored-balls-sorting-in-corner
sh scripts/train_test_single_task.sh data color-coordinated-box-ball-matching
sh scripts/train_test_single_task.sh data color-coordinated-cylinder-tower
sh scripts/train_test_single_task.sh data ball-sorting-with-blocks-barrier
sh scripts/train_test_single_task.sh data build-two-circles
sh scripts/train_test_single_task.sh data cylinder-balancing-and-placement